import styledMap from "styled-map";

export default styledMap`
  alias: alias;
  allScroll: all-scroll;
  cell: cell;
  contextMenu: context-menu;
  colResize: col-resize;
  copy: copy;
  crosshair: crosshair;
  // default: default;
  eResize: e-resize;
  ewResize: ew-resize;
  grab: grab;
  grabbing: grabbing;
  help: help;
  move: move;
  nResize: n-resize;
  neResize: ne-resize;
  neswResize: nesw-resize;
  nsResize: ns-resize;
  nwResize: nw-resize;
  nwseResize: nwse-resize;
  noDrop: no-drop;
  none: none;
  notAllowed: not-allowed;
  pointer: pointer;
  progress: progress;
  rowResize: row-resize;
  sResize: s-resize;
  seResize: se-resize;
  swResize: sw-resize;
  text: text;
  verticalText: vertical-text;
  wResize: w-resize;
  wait: wait;
  zoomIn: zoom-in;
  zoomOut: zoom-out;
  initial: initial;
  inherit: inherit;
  default: pointer;
`;
